### ISSUE TITLE
Update test to fail proplery

### ISSUE THREAD

**Issue by markbasham** [nexusformat/features#22]
currently the bash loop returns the last return code it executes, it would be nice if it returned the sum of them all.

Hopefully Tobias can apply his bash-fu (or is it foo) to this problem

**Comment by zjttoefs** [comment]
Okay, will reverse the order: For every feature test every file. That way we can point out features without working example.

**Comment by zjttoefs** [comment]
@markbasham Either way there will always be a failure in there, because you're guaranteed to test at least one non compliant file. What's the use of the return code?

**Comment by zjttoefs** [comment]
Summary: Return non-zero when there is at least one feature that works with none of the files.

**Comment by zjttoefs** [comment]
The looks like it was successful
