### ISSUE TITLE
Fix error running nxfeature.py with -t option

### ISSUE THREAD

**Issue by matthew-d-jones** [nexusformat/features#8]
The presence of the template recipe added in https://github.com/nexusformat/features/commit/080d1a14a0ea89f3eba60d9b66ba2e4c2f509267 causes running nxfeature.py with the -t flag to fail.
Perhaps the `TEMPLATETEMPLATE` directory could be moved out of `recipes`?

**Comment by markbasham** [comment]
Fixed
